version: '3.8'
services:
  app:
    build: .
    container_name: fastcgi_app
    tty: true
    expose:
      - "9000"
    networks:
      - app_network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

networks:
  app_network:
    driver: bridge